module.exports.drops = [
    ["I can do what I wanna do", "Deko"],
    ["Oh you didn't know bitch, i'm from the moon", "Deko"],
    ["Reaching for the stars got nothin to lose", "Deko"],
    ["Who you finna call with nothin to do?", "Deko"],
    ["Play smash bros, fuck bad hoes, rock tattoos", "Deko"],
    ["Rockin on planets like Thanos", "Deko"],
    ["Pluto almighty will save her", "Deko"],
    ["Young Aphrodite, I slay them", "Deko"],
    ["I swear this night is the greatest", "Deko"],
    ["She ask politely to savour", "Deko"],
    ["Painkiller eschew my favour", "Deko"],
    ["She wants Ciroc guess what flavour", "Deko"],
    ["Bottles are poppin, I made it", "Deko"],
    ["Walk in the mall like i'm famous", "Deko"],
    ["I swear my neck like a glacier", "Deko"],
    ["They look at me like a saviour", "Deko"],
    ["I smile and laugh at the haters", "Deko"],
    ["I can adapt to the changing", "Deko"],
    ["I know i see through the faking", "Deko"],
    ["I know the throne for the taking", "Deko"],
    ["I will arise they will see me", "Deko"],
    ["Why is my life only 3D?", "Deko"],
    ["I see dimensions that need me", "Deko"],
    ["I sip that luxury Fiji", "Deko"],
    ["Capital helps me move freely", "Deko"],
    ["Root of all evil so needed", "Deko"],
    ["Confident, never conceited", "Deko"],
    ["I want control like command prompt", "Deko"],
    ["In my own lane and I can't stop", "Deko"],
    ["Now i'm a cyberpunk phantom", "Deko"],
    ["Barely nocturnal, no Santa", "Deko"],
    ["I want it all I can reach it", "Deko"],
    ["I wanna hear all your secrets", "Deko"],
    ["Don't wanna fall when your sleepy", "Deko"],
    ["She only call when she need me", "Deko"],
    ["You do it all coz youre perfect", "Deko"],
    ["I spend the time coz its worth it", "Deko"],
    ["Give you the moon, you deserve it", "Deko"],
    ["Take over planets desert it", "Deko"],
    ["Don't even care if you hurt em", "Deko"],
    ["Use all that energy wisely", "Deko"],
    ["I know that this is my timing", "Deko"],
    ["I see a spaceship arriving", "Deko"],
    ["Comets colliding, surprising", "Deko"],
    ["Dying inside, i've been fighting", "Deko"],
    ["Dropped outta college, but bitch, I'm still ballin'", "24kGoldn"],
    ["I know that you jealous a little bit", "24kGoldn"],
    ["She seen my picture and heard I'm a singer", "24kGoldn"],
    ["If I pull it out, then she kissin' it", "24kGoldn"],
    ["I'm taking chances and chasing advances", "24kGoldn"],
    ["If life is a bet, then I'm riskin' it", "24kGoldn"],
    ["Skrrt off the block in a Fisker whip", "24kGoldn"],
    ["You know that I had to figure it out", "24kGoldn"],
    ["What would you do for the clout? (Clout)", "24kGoldn"],
    ["Dropped outta college, but bitch, I'm still ballin'", "24kGoldn"],
    ["I know that you jealous a little bit", "24kGoldn"],
    ["Cry to your mama", "24kGoldn"],
    ["You don't want no drama", "24kGoldn"],
    ["Even as a kid you was sensitive", "24kGoldn"],
    ["Flex on the 'Gram, you ain't really rich", "24kGoldn"],
    ["Everyone know that you rented it", "24kGoldn"],
    ["Money, I'm countin' for twenty-four hours", "24kGoldn"],
    ["It's harder to save when it's comin' in", "24kGoldn"],
    ["Can't make a clone 'cause I'm one-of-one", "24kGoldn"],
    ["Lil' boy, you ain't even one of them", "24kGoldn"],
    ["I hit the Bowflex, got my muscle up", "24kGoldn"],
    ["Two twins, tell 'em double dutch", "24kGoldn"],
    ["Two twins, had to double cup", "24kGoldn"],
    ["And they both dance, told 'em, Fuck it up", "24kGoldn"],
    ["Frostbite, Fortnite", "24kGoldn"],
    ["Foreign cars on a foreign line", "24kGoldn"],
    ["Foreign broads and they all fine", "24kGoldn"],
    ["Yeah, yeah, yeah, they all mine", "24kGoldn"],
    ["Switch it up, money dance", "24kGoldn"],
    ["Workin' smart, makin' bands", "24kGoldn"],
    ["Tryna see you drop and get naked, yeah", "24kGoldn"],
    ["Ten, ten, twenties, baby, tryna see you shake it, yeah", "24kGoldn"],
    ["Dropped outta college, but bitch, I'm still ballin'", "24kGoldn"],
    ["I know that you jealous a little bit", "24kGoldn"],
    ["She seen my picture and heard I'm a singer", "24kGoldn"],
    ["If I pull it out, then she kissin' it", "24kGoldn"],
    ["I'm taking chances and chasing advances", "24kGoldn"],
    ["If life is a bet, then I'm riskin' it", "24kGoldn"],
    ["Skrrt off the block in a Fisker whip", "24kGoldn"],
    ["You know that I had to figure it out", "24kGoldn"],
    ["What would you do for the clout? (Clout)", "24kGoldn"],
    ["Dropped outta college, but bitch, I'm still ballin'", "24kGoldn"],
    ["I know that you jealous a little bit", "24kGoldn"],
    ["What don’t you give a fuck about, nigga?", "$NOT"],
    ["I’on give a fuck about... hmm", "$NOT"],
    ["Nice chain, red Balmains (Ayy)", "$NOT"],
    ["Chain swang, like Pretty Things (Yuh)", "$NOT"],
    ["Kick a bitch, call me Liu Kang (Liu Kang)", "$NOT"],
    ["Dumb bitch, give me dumb brain, yuh", "$NOT"],
    ["Wrist wet, wet like rain (Ayy)", "$NOT"],
    ["Nike Swoosh, White Cocaines (Cocaína)", "$NOT"],
    ["Iceberg, that’s Gucci Mane (Burr)", "$NOT"],
    ["Tall racks like Yao Ming (Yao Ming)", "$NOT"],
    ["Fuck school, I don't fuck with rules (I’on fuck with 'em)", "$NOT"],
    ["Laid back, nigga, always keep a tool (Keep a tool)", "$NOT"],
    ["You a pussy nigga, you a fuckin’ fool (You a fool)", "$NOT"],
    ["Wait, hold up, ayy, ayy", "$NOT"],
    ["Bitches look at me like I am a jewel (Like a jewel)", "$NOT"],
    ["I be posted wit’ yo’ bitch in the pool (In the pool)", "$NOT"],
    ["Blast off—wait, ah, jet fuel (Jet fuel)", "$NOT"],
    ["Fuck this world, man, these bitches so cruel (So cruel)", "$NOT"],
    ["What you want from me, Mercedes AMG? (AMG)", "$NOT"],
    ["Push to start, bitch, no keys (No keys)", "$NOT"],
    ["They don’t gotta know about you and me (Nah)", "$NOT"],
    ["You the only one I know and I trust (And I trust)", "$NOT"],
    ["Baby, you my Angel in the Stardust", "$NOT"],
    ["Niggas always wanna act so tough (So tough)", "$NOT"],
    ["Blade it out, phew, phew, see the cuts (See the cuts)", "$NOT"],
    ["I be with my soldiers, eatin’ chicken wings (Chicken wings)", "$NOT"],
    ["Nigga, you can’t hang, this is not your game (Not your game)", "$NOT"],
    ["Black fit, Gosha, Gosha, gold fangs (Gold fangs)", "$NOT"],
    ["Long clip, Gosha, Gosha, bang, bang (Bang, bang)", "$NOT"],
    ["Black fit, Gosha, Gosha, gold fangs (Gold fangs)", "$NOT"],
    ["Long clip, Gosha, Gosha, bang, bang (Bang, bang)", "$NOT"],
    ["Black fit, Gosha, Gosha, gold fangs (Gold fangs)", "$NOT"],
    ["Bro's on your block with that Glock, right now (Ooh, hey, ayy, too much, ooh)", "XXXTENTACION"],
    ["Try me like an Opp (Ayy!) and indeed, get shot down, okay (Hey, ooh)", "XXXTENTACION"],
    ["Ayy she wanna, she wanna l-l-lick my dick like- like a what? (Nice!) (Hey, hey, hey, ooh, hey, ooh, hey, huh, yah)", "XXXTENTACION"],
    ["Lick my dick like Lil Wayne lollipop, huh! (Huh, yah, hoo)", "XXXTENTACION"],
    ["Hi, my name's Ryan! (Yeah, hey, hey, hey, hey, ooh, ayy)", "XXXTENTACION"],
    ["What do they call me? Call me wolf in sheep's skin? (Yah, ayy, ayy, yah, ahoo)", "XXXTENTACION"],
    ["Try me, might fight (Ayy), fist fuck, on sight", "XXXTENTACION"],
    ["Wrist heavy, fat dyke, pop Molly, Mike Ike", "XXXTENTACION"],
    ["I got glacial white ice and my bitch rack nice", "XXXTENTACION"],
    ["And I do fight dykes, ride my dick like a bike (Ayy, ayy, ayy)", "XXXTENTACION"],
    ["I got black in my voots (Yah, ooh), my name's Toby, like I'm Roots (Ayy, wow)", "XXXTENTACION"],
    ["Grab that bat, Hey Bruce (Hey, hey, hey), swing that bitch might lose a tooth (Whatever)", "XXXTENTACION"],
    ["She suck dick with no tooth (Hey, hey), my nose runny like, Achoo", "XXXTENTACION"],
    ["With that pussy (Hey, hey), I got coins, might insert right in her groin", "XXXTENTACION"],
    ["It's like jelly, ayy (Wow, hey), dick right in her belly, uh, yuh (Ow!)", "XXXTENTACION"],
    ["Baby got back, yuh (Hey), bitch, come look at my tats, (Damn!) uh, yuh", "XXXTENTACION"],
    ["You got taxed (Hey, hey), yuh, my head be like Bratz, uh, yuh (Hey, hey)", "XXXTENTACION"],
    ["Dump that bitch (Woo), yuh, who gonna hold my racks, uh, huh (Yah)", "XXXTENTACION"],
    ["I'm like, \"Bitch, who is your mans?\" (Ayy)", "XXXTENTACION"],
    ["Can't keep my dick in my pants (Ayy)", "XXXTENTACION"],
    ["My bitch don't love me no mo' (Ayy)", "XXXTENTACION"],
    ["She kick me out, I'm like, \"Vro\" (Ayy)", "XXXTENTACION"],
    ["That bitch don't wanna be friends (Ayy)", "XXXTENTACION"],
    ["I gave her dick, she amen (Ayy)", "XXXTENTACION"],
    ["She put her tongue on my dick (Ayy)", "XXXTENTACION"],
    ["Look at my wrist, about ten (Ayy)", "XXXTENTACION"],
    ["Just got a pound of the boof (Ayy)", "XXXTENTACION"],
    ["Brought that shit straight to the booth (Ayy)", "XXXTENTACION"],
    ["Tommy my Hilfiger voots (Ayy)", "XXXTENTACION"],
    ["She said, \"Wan' fuck?\" Bitch, I do (Ayy)", "XXXTENTACION"],
    ["You put a gun on my mans (Ayy)", "XXXTENTACION"],
    ["I put a hole in your parents (Ayy)", "XXXTENTACION"],
    ["I just got lean on my Ksubis (Ayy)", "XXXTENTACION"],
    ["I got a Uzi, no Uzi", "XXXTENTACION"],
    ["Fuck on me, look at me, ayy", "XXXTENTACION"],
    ["Fuck on me, yah, look at me, ayy", "XXXTENTACION"],
    ["Look at me, look at me, yah", "XXXTENTACION"],
    ["Look at me, yah, fuck on me", "XXXTENTACION"],
    ["Look at me, fuck on me, yah", "XXXTENTACION"],
    ["Tell these fuck niggas, voot me up, pipe up", "XXXTENTACION"],
    ["Ayy, shouts out Bans and them, ayy", "XXXTENTACION"],
    ["I took a white bitch to Starbucks", "XXXTENTACION"],
    ["That little bitch got her throat fucked", "XXXTENTACION"],
    ["I like to rock out like I'm misfit", "XXXTENTACION"],
    ["My emo bitch like her wrist slit", "XXXTENTACION"],
    ["Curly hair bitch like I'm Corbin", "XXXTENTACION"],
    ["Got like three bitches, I'm Mormon", "XXXTENTACION"],
    ["Skeet on your main bitch's forehead", "XXXTENTACION"],
    ["Don't want your pussy, just want head", "XXXTENTACION"],
    ["Look at me, fuck on me", "XXXTENTACION"],
    ["Look at me, yah, ayy!", "XXXTENTACION"],
    ["Look at me, yah!", "XXXTENTACION"],
    ["I can't take this one more time", "two:22"],
    ["I fell upon a knife", "two:22"],
    ["Searching for you and I", "two:22"],
    ["The creation of a star", "two:22"],
    ["No one sees from the start", "two:22"],
    ["An explosion from afar", "two:22"],
    ["Hard to see what’s in your heart", "two:22"],
    ["Imagine what we'll see", "two:22"],
    ["Another reality", "two:22"],
    ["With their personalities", "two:22"],
    ["Switched showing who they'll be", "two:22"],
    ["I think I lost my mind", "two:22"],
    ["Somewhere no one can find", "two:22"],
    ["We’re all one of a kind", "two:22"],
    ["Some brighter with their shine", "two:22"],
    ["She'll never love what I want her to", "two:22"],
    ["Her stare goes through away to you", "two:22"],
    ["Guide me on my way", "two:22"],
    ["Seeking out a happy day", "two:22"],
    ["Forever floating away", "two:22"],
    ["In my life, no one will stay", "two:22"],
    ["I can't take this one more time", "two:22"],
    ["I fell upon a knife", "two:22"],
    ["Searching for you and I", "two:22"],
    ["You pick me up to tear me down", "two:22"],
    ["I hate myself when you’re around", "two:22"],
    ["I’m such a clown, but I still need you now", "two:22"],
    ["Cloak of shadows in the night", "two:22"],
    ["Stay with me, I’ll make it right", "two:22"],
    ["There’s nothing left inside", "two:22"],
    ["Don’t tell me that you think I’m fine", "two:22"],
    ["I swear I fucking hate that lie", "two:22"],
    ["At times I know I’m not alright, so don’t you even try", "two:22"],
    ["Frigid bones are shaken cold", "two:22"],
    ["A little kid, a tortured soul", "two:22"],
    ["A heart of gold", "two:22"],
    ["It’s time we said goodbye", "two:22"],
    ["Don’t try and change my mind", "two:22"],
    ["Gone down a thousand times", "two:22"],
    ["Take me far from here", "two:22"],
    ["In your atmosphere", "two:22"],
    ["Cause I, will try, every night, so", "two:22"],
    ["Whittled curves", "two:22"],
    ["Can shape the lines", "two:22"],
    ["But every time it’s just so damn hard to find, I notice every night", "two:22"],
    ["A fallen torch of leaking dread", "two:22"],
    ["No one else to hold instead", "two:22"],
    ["Something just so hard to bend", "two:22"],
    ["Up until the very end", "two:22"],
    ["And I feel the cold girl I'm frostbit", "Savage Ga$p"],
    ["I can feel the flow of your soul from your soft lips", "Savage Ga$p"],
    ["And maybe me and you could be us", "Savage Ga$p"],
    ["Lately you ain't really even there like a beat cut", "Savage Ga$p"],
    ["And I can see the visions in me dreams of a love that I been missing I been wishin' you to be", "Savage Ga$p"],
    ["Cut myself to ribbons you can see", "Savage Ga$p"],
    ["Hard to keep myself together when splitting at the seams", "Savage Ga$p"],
    ["Getting tougher as the years pass", "Savage Ga$p"],
    ["Bullet for my valentine I can feel your tears crash", "Savage Ga$p"],
    ["And I know that you can feel that", "Savage Ga$p"],
    ["Maybe we can make it to the point where you can heal back", "Savage Ga$p"],
    ["Put me back together like you namine", "Savage Ga$p"],
    ["Memories fading from my mind into the common space", "Savage Ga$p"],
    ["And I just hate this place", "Savage Ga$p"],
    ["I just want to die and escape this fate", "Savage Ga$p"],
    ["I need my mind erased", "Savage Ga$p"],
    ["I'll give you the stars never mind some space", "Savage Ga$p"],
    ["Am I replaced", "Savage Ga$p"],
    ["A sea of damned, a tidal wave", "Savage Ga$p"],
    ["What the fuck", "Savage Ga$p"],
    ["I’m so drunk", "Savage Ga$p"],
    ["Damn i think that I’m in love", "Savage Ga$p"],
    ["But my friends like naw you just drunk as fuck like um", "Savage Ga$p"],
    ["What the fuck", "Savage Ga$p"],
    ["I’m in love", "Savage Ga$p"],
    ["I'mma Try call you up", "Savage Ga$p"],
    ["But you like boy you drunk and I’m hanging up", "Savage Ga$p"],
    ["Can you give it to me straight", "Savage Ga$p"],
    ["I don’t wanna go but I know that it’s fate", "Savage Ga$p"],
    ["With that motherfucking rose gold glow in your face", "Savage Ga$p"],
    ["I don’t know where to go", "Savage Ga$p"],
    ["We should go get away", "Savage Ga$p"],
    ["Pull up on em dripping in ysl, like wow", "Savage Ga$p"],
    ["I see you glistening in the light now", "Savage Ga$p"],
    ["Night mode", "Savage Ga$p"],
    ["I just wanna look into your bright smile", "Savage Ga$p"],
    ["I want you back up in my life girl", "Savage Ga$p"],
    ["Sorry that I missed your text", "Savage Ga$p"],
    ["I’m just really fucking drunk and I just miss my ex", "Savage Ga$p"],
    ["I just wanna let her know that I see her friends", "Savage Ga$p"],
    ["That I always ask about her wonder how she’s been", "Savage Ga$p"],
    ["God really snapped when he made you", "Savage Ga$p"],
    ["I'mma call your parents say thank you", "Savage Ga$p"],
    ["And I know I’m out of pocket", "Savage Ga$p"],
    ["But I say maybe we should try a redo", "Savage Ga$p"],
    ["What the fuck, I’m so drunk", "Savage Ga$p"],
    ["Damn i think that I’m in love", "Savage Ga$p"],
    ["But my friends like naw you just drunk as fuck like um", "Savage Ga$p"],
    ["What the fuck", "Savage Ga$p"],
    ["I’m in love", "Savage Ga$p"],
    ["I'mma try call you up", "Savage Ga$p"],
    ["But you like boy you drunk and I’m hanging up", "Savage Ga$p"],
    ["Take me back to the days", "Savage Ga$p"],
    ["Up in your 01 mustang", "Savage Ga$p"],
    ["Back when you would love me", "Savage Ga$p"],
    ["Back before we had the drug problems and trust things", "Savage Ga$p"],
    ["Back when I would only care for one thing", "Savage Ga$p"],
    ["I know summer doesn’t last forever", "Savage Ga$p"],
    ["I think we can grow old together", "Savage Ga$p"],
    ["Remember what I told you", "Savage Ga$p"],
    ["I would really jump up in the sky and put my feelings to the side and and hold the galaxy before you", "Savage Ga$p"],
    ["I would hold the sun up to warm you", "Savage Ga$p"],
    ["I would hold the moon so you glow too", "Savage Ga$p"],
    ["I just gotta say girl I really got these flaming hot Cheetos on my fingers I’m tryna hold you", "Savage Ga$p"],
    ["I'm tryna hold you", "Savage Ga$p"],
    ["What's poppin'? (Pooh, you a fool for this one)", "Jack Harlow"],
    ["Brand new whip just hopped in (Just hopped in)", "Jack Harlow"],
    ["I got options (Oh Lord, Jetson made another one)", "Jack Harlow"],
    ["I could pass that bitch like Stockton (It ain't nothin')", "Jack Harlow"],
    ["Just joshin'", "Jack Harlow"],
    ["I'ma spend this holiday locked in (Ooh)", "Jack Harlow"],
    ["My body got rid of them toxins (Mmh, mmh)", "Jack Harlow"],
    ["SportsCenter, top ten", "Jack Harlow"],
    ["I could put the ball in the end zone, put a bad bitch in the friendzone, ooh", "Jack Harlow"],
    ["This shit sound like an intro, Jetson, give me that tempo, ooh", "Jack Harlow"],
    ["Told Pooh he a fool with this shit (He a fool)", "Jack Harlow"],
    ["Told her don't let her friends know (Don't)", "Jack Harlow"],
    ["In the 'Ville and I move like a don (Don)", "Jack Harlow"],
    ["Eating fettuccine at Vincenzo's", "Jack Harlow"],
    ["Me and my 'migos got that free smoke", "Jack Harlow"],
    ["On the West Coast, yeah, I'm talking 'bout pre-rolls (Pre-roll)", "Jack Harlow"],
    ["Dark haired bitch and she look like Shego (She do)", "Jack Harlow"],
    ["Hometown hero, feeling myself, can't murder my ego (Can't do it)", "Jack Harlow"],
    ["She heard of my deep stroke", "Jack Harlow"],
    ["She said, \"Babe, does it hurt when I deep throat?\" (It does)", "Jack Harlow"],
    ["Certified freak ho", "Jack Harlow"],
    ["Hang around us and she learnin' my lingo", "Jack Harlow"],
    ["Back then, wasn't worried 'bout me though", "Jack Harlow"],
    ["In the gym tryna work on my free throw, goddamn", "Jack Harlow"],
    ["Spending money at the club like Sam's (Cha-ching)", "Jack Harlow"],
    ["Yes, ma'am", "Jack Harlow"],
    ["She a lil' freak on cam", "Jack Harlow"],
    ["But she don't put this on the 'Gram (Nah)", "Jack Harlow"],
    ["Lil' boys tryna diss on the 'Gram (Ayy)", "Jack Harlow"],
    ["I can't switch on the fam (Bitch)", "Jack Harlow"],
    ["Shit's hot, hit the switch on the fan (Hit that shit)", "Jack Harlow"],
    ["This where my head is (Listen)", "Jack Harlow"],
    ["I feel resentment from every direction", "Jack Harlow"],
    ["Even some homies be wearing expressions", "Jack Harlow"],
    ["I be discouraged from sharing my blessings (Damn)", "Jack Harlow"],
    ["We used to share a connection", "Jack Harlow"],
    ["Now it just feels like it's wearing and stretching", "Jack Harlow"],
    ["I'm getting real sick of taking advice", "Jack Harlow"],
    ["From people that never could stare at reflections (Ooh)", "Jack Harlow"],
    ["Somewhere in there is a lesson", "Jack Harlow"],
    ["Y'all ain't evolvin', it's very depressing", "Jack Harlow"],
    ["I'm at the club with the basketball team", "Jack Harlow"],
    ["Me and the Cardinals are sharing a section (Facts)", "Jack Harlow"],
    ["Gotta cherish the present", "Jack Harlow"],
    ["I'm drinking water and wearing protection", "Jack Harlow"],
    ["Got a career and I'm very invested", "Jack Harlow"],
    ["Some people call it a scary obsession (Ooh, period, but)", "Jack Harlow"],
    ["I like to call it a passion, I can't be sitting relaxin' (Nah, I can't)", "Jack Harlow"],
    ["PG, we getting some traction, I'm at the venue, it's packed in (Packed out)", "Jack Harlow"],
    ["I'm digging her accent", "Jack Harlow"],
    ["I got a B.B. Simon belt on me and she tryna get it unfastened", "Jack Harlow"],
    ["That's my type of distraction, that's my type and she Latin (That's facts, ooh)", "Jack Harlow"],
    ["Got my own flow and I'm 'bout to get a patent", "Jack Harlow"],
    ["Brand new sheets for the bed, they satin (Soft, real soft)", "Jack Harlow"],
    ["Y'all wasn't tuned in back then (Nah)", "Jack Harlow"],
    ["My swag, they keep jackin' (Keep on jackin')", "Jack Harlow"],
    ["I ain't doin' no verse, quit askin' (Quit askin')", "Jack Harlow"],
    ["What's poppin'? (Pooh, you a fool for this one)", "Jack Harlow"],
    ["Brand new whip just hopped in (Just hopped in)", "Jack Harlow"],
    ["I got options", "Jack Harlow"],
    ["I could pass that bitch like Stockton (It ain't nothin')", "Jack Harlow"],
    ["Just joshin'", "Jack Harlow"],
    ["I'ma spend this holiday locked in (Ooh)", "Jack Harlow"],
    ["My body got rid of them toxins (Mmh, mmh)", "Jack Harlow"],
    ["SportsCenter, top ten", "Jack Harlow"],
    ["Too stylish", "Jack Harlow"],
    ["She too fly", "Jack Harlow"],
    ["Make me lose balance", "Jack Harlow"],
    ["Back it up, like we taking over for the '99", "Jack Harlow"],
    ["And the 2000's", "Jack Harlow"],
    ["The city that's mine", "Jack Harlow"],
    ["I need a new challenge", "Jack Harlow"],
    ["I can't tell if you 'bout it", "Jack Harlow"],
    ["I doubt it", "Jack Harlow"],
    ["Baddies at the club and they got ya boy surrounded", "Jack Harlow"],
    ["She want me to pound it", "Jack Harlow"],
    ["Said she want my kids but they grounded", "Jack Harlow"],
    ["I been staying focused, got me celibate", "Jack Harlow"],
    ["I could be selling dick", "Jack Harlow"],
    ["Now I'm in my element", "Jack Harlow"],
    ["Y'all boys' irrelevant", "Jack Harlow"],
    ["Me and Jenius, we got hella hits", "Jack Harlow"],
    ["I don't know what jealous is", "Jack Harlow"],
    ["'Cause I ain't never felt the shit", "Jack Harlow"],
    ["Feeling like myself again", "Jack Harlow"],
    ["Feeling like the man", "Jack Harlow"],
    ["I got some stories I can tell my kids", "Jack Harlow"],
    ["You got some stories you can tell your friends", "Jack Harlow"],
    ["About my grace and my elegance", "Jack Harlow"],
    ["Too stylish", "Jack Harlow"],
    ["She too fly", "Jack Harlow"],
    ["Make me lose balance", "Jack Harlow"],
    ["Back it up, like we taking over for the '99", "Jack Harlow"],
    ["And the 2000's", "Jack Harlow"],
    ["The city that's mine", "Jack Harlow"],
    ["I need a new challenge", "Jack Harlow"],
    ["I can't tell if you 'bout it", "Jack Harlow"],
    ["She on that Smirnoff Ice", "Jack Harlow"],
    ["Get right to it, we don't turn off lights", "Jack Harlow"],
    ["She done got some money now she wear Off White", "Jack Harlow"],
    ["Off of the white, got her turnt all night", "Jack Harlow"],
    ["All right (All right)", "Jack Harlow"],
    ["Them boys said on sight, it's all lies, yeah", "Jack Harlow"],
    ["Big dog to these small fries, yeah", "Jack Harlow"],
    ["Tens with me, you got all fives, yeah", "Jack Harlow"],
    ["I might be the greatest all time", "Jack Harlow"],
    ["Too stylish", "Jack Harlow"],
    ["She too fly", "Jack Harlow"],
    ["Make me lose balance", "Jack Harlow"],
    ["Back it up, like we taking over for the '99", "Jack Harlow"],
    ["And the 2000's", "Jack Harlow"],
    ["The city that's mine", "Jack Harlow"],
    ["I need a new challenge", "Jack Harlow"],
    ["I can't tell if you 'bout it", "Jack Harlow"],
    ["Too stylish", "Jack Harlow"],
    ["She too fly", "Jack Harlow"],
    ["Make me lose balance", "Jack Harlow"],
    ["Back it up, like we taking over for the '99", "Jack Harlow"],
    ["And the 2000's", "Jack Harlow"],
    ["The city that's mine", "Jack Harlow"],
    ["I need a new challenge", "Jack Harlow"],
    ["I can't tell if you 'bout it", "Jack Harlow"],
    ["I wanna see some ass", "Jack Harlow"],
    ["I wanna see some ass", "Jack Harlow"],
    ["Baby, can you do it like that?", "Jack Harlow"],
    ["From the front to the back", "Jack Harlow"],
    ["She said, \"I don't wanna move too fast\"", "Jack Harlow"],
    ["'Til she hit that gas", "Jack Harlow"],
    ["Ciroc and the puff puff pass", "Jack Harlow"],
    ["Now the whole squad getting fucked up fast", "Jack Harlow"],
    ["She said, \"Jack, where you been at?\"", "Jack Harlow"],
    ["On the road, but I just got back", "Jack Harlow"],
    ["And I'm still flyer than a bitch", "Jack Harlow"],
    ["And ya boyfriend, well he just not that", "Jack Harlow"],
    ["And I, I don't know how to behave", "Jack Harlow"],
    ["I'ma tell her be safe", "Jack Harlow"],
    ["I don't need the pussy, I'ma tell her be safe", "Jack Harlow"],
    ["I got God with me and he's telling me things", "Jack Harlow"],
    ["I wanna see some ass", "Jack Harlow"],
    ["I wanna see some ass", "Jack Harlow"],
    ["Baby, can you do it like that?", "Jack Harlow"],
    ["From the front to the back", "Jack Harlow"],
    ["She said, \"I don't wanna move too fast\"", "Jack Harlow"],
    ["'Til she hit that gas", "Jack Harlow"],
    ["Ciroc and the puff puff pass", "Jack Harlow"],
    ["Now the whole squad getting fucked up fast", "Jack Harlow"],
    ["Ooh, I'm just tryna' see something", "Jack Harlow"],
    ["I ain't gotta say it 'cause they know where we from", "Jack Harlow"],
    ["I got some money out the ATM, but I'm gonna keep some", "Jack Harlow"],
    ["Strip club, pre-cum off of the liquor, fell in love with a stripper", "Jack Harlow"],
    ["Now I'm asking her where she from", "Jack Harlow"],
    ["As if we gon' be something", "Jack Harlow"],
    ["I wanna be something", "Jack Harlow"],
    ["Take my number down, you can hit me if you need some'", "Jack Harlow"],
    ["Said she got three sons", "Jack Harlow"],
    ["Do you want four? 'Cause I need one", "Jack Harlow"],
    ["Do you got whores? 'Cause I'll be one", "Jack Harlow"],
    ["Going all night like the reruns", "Jack Harlow"],
    ["I wanna see some ass", "Jack Harlow"],
    ["I wanna see some ass", "Jack Harlow"],
    ["Baby, can you do it like that?", "Jack Harlow"],
    ["From the front to the back", "Jack Harlow"],
    ["She said, \"I don't wanna move too fast\"", "Jack Harlow"],
    ["'Til she hit that gas", "Jack Harlow"],
    ["Ciroc and the puff puff pass", "Jack Harlow"],
    ["Now the whole squad getting fucked up fast", "Jack Harlow"],
    ["Hey, big head", "Jack Harlow"],
    ["I'm locked in tryna' make this bread (Woo)", "Jack Harlow"],
    ["I can't keep on giving you time", "Jack Harlow"],
    ["I got cash to make instead (Cash)", "Jack Harlow"],
    ["She wanna fuck me one-on-one", "Jack Harlow"],
    ["We might run that train instead", "Jack Harlow"],
    ["Me and my friend just like twins", "Jack Harlow"],
    ["Same nutsack and the same dick head (What the fuck?)", "Jack Harlow"],
    ["Seen that bitch and we ain't impressed (Woo)", "Jack Harlow"],
    ["Thick brunette and she came from Lex", "Jack Harlow"],
    ["Phone got bugs and they ain't insects", "Jack Harlow"],
    ["Feds tuned in when I send my texts", "Jack Harlow"],
    ["Ain't nobody worried 'bout if I'm next", "Jack Harlow"],
    ["'Cause they know I'm next", "Jack Harlow"],
    ["I thank God, I know I'm blessed", "Jack Harlow"],
    ["I recall when you threw shade", "Jack Harlow"],
    ["I can let that shit go, I guess", "Jack Harlow"],
    ["I'm locked in, had to go out less", "Jack Harlow"],
    ["Everybody act like they know best (Know best)", "Jack Harlow"],
    ["Her boyfriend ain't fresh", "Jack Harlow"],
    ["Look like someone I'm gon' outdress", "Jack Harlow"],
    ["She’s so wet, had to hold my breath", "Jack Harlow"],
    ["Ain't hit since, she know I'm pressed (Fucked up about it)", "Jack Harlow"],
    ["Show my chest, let me flex, bitch (Ha)", "Jack Harlow"],
    ["In the flesh, got connects down in Texas (Woo)", "Jack Harlow"],
    ["Pussy juice, side of eggs, that's my breakfast", "Jack Harlow"],
    ["Sugar mama, 56, off of Craigslist (Ayy)", "Jack Harlow"],
    ["Can we have a threesome with your fuckin' best friend?", "Jack Harlow"],
    ["I ain't talking Florida when I say I'm destined", "Jack Harlow"],
    ["She ain't know my money taller than a Westin", "Jack Harlow"],
    ["Hotel, got your bitches checked in", "Jack Harlow"],
    ["Ex-chick salty just like Chex Mix (Uh)", "Jack Harlow"],
    ["Cop a plane ticket for my new chick once the check hits", "Jack Harlow"],
    ["I come from a city that is very much eclectic", "Jack Harlow"],
    ["But it's got another side to it that gets hectic", "Jack Harlow"],
    ["Shorty that I mess with got a friend that's a detective", "Jack Harlow"],
    ["She gon' run surveillance just to find out who I've slept with", "Jack Harlow"],
    ["All my jewelry gifted just like me, ain't bought a necklace", "Jack Harlow"],
    ["I'm not young and reckless, bitch, I'm cool, calm, and collected (Collected)", "Jack Harlow"],
    ["Flexin', I'm the one that she texting (Texting)", "Jack Harlow"],
    ["Lightskin from DC like the Redskins (Redskins)", "Jack Harlow"],
    ["These rappers falling off just like dead skin", "Jack Harlow"],
    ["I set trends, next up, no question (No question)", "Jack Harlow"],
    ["I don't want a valentine", "24kGoldn"],
    ["I just want Valentino", "24kGoldn"],
    ["I just want the neck", "24kGoldn"],
    ["I poker face like a casino", "24kGoldn"],
    ["Deep throat, know I get it in like a free throw", "24kGoldn"],
    ["Shawty want some more", "24kGoldn"],
    ["She just can't seem to keep her knees closed", "24kGoldn"],
    ["I-I-I don't want a valentine", "24kGoldn"],
    ["I just want Valentino", "24kGoldn"],
    ["I just want the neck", "24kGoldn"],
    ["I poker face like a casino", "24kGoldn"],
    ["Deep throat, know I get it in like a free throw", "24kGoldn"],
    ["Shawty want some more", "24kGoldn"],
    ["She just can't seem to keep her knees closed", "24kGoldn"],
    ["I fuck her long, ain't no Minute Maid", "24kGoldn"],
    ["My diamonds lemonade", "24kGoldn"],
    ["Flexing hard, call me Popeye", "24kGoldn"],
    ["Wallet filled with spinach ay", "24kGoldn"],
    ["Cut you off on the interstate", "24kGoldn"],
    ["I'm first to finish, ay", "24kGoldn"],
    ["I'm a young rich nigga", "24kGoldn"],
    ["Bitch it's always been that way", "24kGoldn"],
    ["To the grave, might just be tomorrow", "24kGoldn"],
    ["Might just be today", "24kGoldn"],
    ["So i always live it up, we poppin' bottles, poppin' Ks", "24kGoldn"],
    ["Gucci shades from my boujee bitch, ain't even had to pay", "24kGoldn"],
    ["Had to put on for the team", "24kGoldn"],
    ["And had to put on for the bay", "24kGoldn"],
    ["I'm so fly when I rock robins wings", "24kGoldn"],
    ["I can't stay in one place", "24kGoldn"],
    ["Russian cremes in my rocket ship", "24kGoldn"],
    ["We go to outer space", "24kGoldn"],
    ["Mask off, mask on, fuck it", "24kGoldn"],
    ["I can't catch a case", "24kGoldn"],
    ["Blast off, blast off", "24kGoldn"],
    ["See the stars up in wraith", "24kGoldn"],
    ["You can't get into the crib", "24kGoldn"],
    ["Because the mansion got a gate", "24kGoldn"],
    ["You can't come into my section", "24kGoldn"],
    ["I'm gon' put you in your place", "24kGoldn"],
    ["If the club goin' up", "24kGoldn"],
    ["You bet I'm sliding like a chase", "24kGoldn"],
    ["And i think I fell in love", "24kGoldn"],
    ["She shook that ass up in my face", "24kGoldn"],
    ["I don't want a valentine", "24kGoldn"],
    ["I just want Valentino", "24kGoldn"],
    ["I just want the neck", "24kGoldn"],
    ["I poker face like a casino", "24kGoldn"],
    ["Deep throat", "24kGoldn"],
    ["Know I get it in like a free throw", "24kGoldn"],
    ["Shawty want some more", "24kGoldn"],
    ["She just can't seem to keep her knees closed", "24kGoldn"],
    ["I-I-I don't want a valentine", "24kGoldn"],
    ["I just want Valentino", "24kGoldn"],
    ["I just want the neck", "24kGoldn"],
    ["I poker face like a casino", "24kGoldn"],
    ["Deep throat", "24kGoldn"],
    ["Know I get it in like a free throw", "24kGoldn"],
    ["Shawty want some more", "24kGoldn"],
    ["She just can't seem to keep her knees closed", "24kGoldn"],
    ["I-I-I-I don't want a valentine", "24kGoldn"],
    ["I just want Valentino", "24kGoldn"],
    ["I just want the neck", "24kGoldn"],
    ["I poker face like a casino", "24kGoldn"],
    ["Deep throat", "24kGoldn"],
    ["Know I get it in like a free throw", "24kGoldn"],
    ["Shawty want some more", "24kGoldn"],
    ["She just can't seem to keep her knees closed", "24kGoldn"],
    ["I-I-I don't want a valentine", "24kGoldn"],
    ["I just want Valentino", "24kGoldn"],
    ["I just want the neck", "24kGoldn"],
    ["I poker face like a casino", "24kGoldn"],
    ["Deep throat", "24kGoldn"],
    ["Know I get it in like a free throw", "24kGoldn"],
    ["Shawty want some more", "24kGoldn"],
    ["She just can't seem to keep her knees closed", "24kGoldn"],
    ["Я срываю твою шкуру", "ВУЛЬФ"],
    ["Сиги  об себя тушу", "ВУЛЬФ"],
    ["Я  реально жёсткий парень", "ВУЛЬФ"],
    ["И ни разу не шучу, я", "ВУЛЬФ"],
    ["Эй‚ эй‚ эй‚ алкоголь каждый день", "ВУЛЬФ"],
    ["Хочу  сдохнуть побыстрей", "ВУЛЬФ"],
    ["Огненный  как прометей", "ВУЛЬФ"],
    ["Вызывай своих людей", "ВУЛЬФ"],
    ["Начинается  война", "ВУЛЬФ"],
    ["Нету способов бежать и я готовлюсь убивать, воу", "ВУЛЬФ"],
    ["Эта штука - hardcore", "ВУЛЬФ"],
    ["Я стреляю headshot, и теперь мне хорошо", "ВУЛЬФ"],
    ["Убивай  всех этих недоумков своими руками", "ВУЛЬФ"],
    ["Позови меня к себе‚ подруга, если заскучала", "ВУЛЬФ"],
    ["Глаза за синяками, помоги мне мама", "ВУЛЬФ"],
    ["Я в жизни потерялся‚ так-то нихуя не знаю", "ВУЛЬФ"],
    ["Ментальный импотент, на вас всех кладу я хер", "ВУЛЬФ"],
    ["Избегаю я проблем, нахуй оно надо мне?", "ВУЛЬФ"],
    ["Ментальный импотент, на вас всех я кладу хер", "ВУЛЬФ"],
    ["Избегаю я проблем, нахуй оно надо мне?", "ВУЛЬФ"],
    ["I don't give a shit", "GHOSTOFBLU"],
    ["You can fuck with it", "GHOSTOFBLU"],
    ["You can't fuck with us", "GHOSTOFBLU"],
    ["Put you on a blacklist", "GHOSTOFBLU"],
    ["I don't give a shit", "GHOSTOFBLU"],
    ["You can fuck with this", "GHOSTOFBLU"],
    ["You can't fuck with us", "GHOSTOFBLU"],
    ["Put you on a blacklist", "GHOSTOFBLU"],
    ["Stay so fresh, so clean, think they like me (like me)", "Lil Uzi Vert"],
    ["I wear more Supreme than a hypebeast (than a hypebeast)", "Lil Uzi Vert"],
    ["Only blue, no green don't excite me (excite me)", "Lil Uzi Vert"],
    ["I could make a ho out your wifey (out your wifey)", "Lil Uzi Vert"],
    ["Jeremy Scott up on my toes, act like Shockey (whoa)", "Lil Uzi Vert"],
    ["Made her get down on the bottom and she top me (let's go)", "Lil Uzi Vert"],
    ["Pull up extra icy, I'm not playin' hockey (bling, blaow)", "Lil Uzi Vert"],
    ["Niggas think I'm weird and they don't really like me (like me)", "Lil Uzi Vert"],
    ["'Cause I could fuck your bitch and fuck your mom and auntie (yeah)", "Lil Uzi Vert"],
    ["Your girl's a five but your mom is a dime piece (ayy)", "Lil Uzi Vert"],
    ["And your auntie, her name is Miss Connie (Miss Connie)", "Lil Uzi Vert"],
    ["I got one Glock, his name Clyde, the other one named Bonnie (let's go)", "Lil Uzi Vert"],
    ["These bitches, they think they dandy but they be just lyin' (bitches lie)", "Lil Uzi Vert"],
    ["That lil' bitch, can't throw it back, I swear that ho be tryin'", "Lil Uzi Vert"],
    ["When I fuck her from the front it sound like that bitch dyin' (on God)", "Lil Uzi Vert"],
    ["VVS, I need a vest, anemic my diamonds (whoa)", "Lil Uzi Vert"],
    ["I swear these niggas talk shit but they really be hidin' (woo)", "Lil Uzi Vert"],
    ["Had that boy's bitch on my dick, that ho, she was just ridin'", "Lil Uzi Vert"],
    ["Diamonds on my neck so wet, that shit look like Poseidon (so wet)", "Lil Uzi Vert"],
    ["I stand on my money then my height, it turn to 9'10\" (yeah)", "Lil Uzi Vert"],
    ["Yeah, these niggas be bitin' (fuck)", "Lil Uzi Vert"],
    ["Grra-ta, I'm not really with the fightin' (grra-ta)", "Lil Uzi Vert"],
    ["Yeah, me and her was vibin' (yeah, vibin')", "Lil Uzi Vert"],
    ["Yeah, yeah", "Lil Uzi Vert"],
    ["Your bitch call me \"Myron\" (call me)", "Lil Uzi Vert"],
    ["Stay so fresh, so clean, think they like me (like me)", "Lil Uzi Vert"],
    ["I wear more Supreme than a hypebeast (than a hypebeast)", "Lil Uzi Vert"],
    ["Only blue, no green don't excite me (excite me)", "Lil Uzi Vert"],
    ["I could make a ho out your wifey (out your wifey)", "Lil Uzi Vert"],
    ["Jeremy Scott up on my toes, act like Shockey (whoa)", "Lil Uzi Vert"],
    ["Made her get down on the bottom and she top me (let's go)", "Lil Uzi Vert"],
    ["Pull up extra icy, I'm not playin' hockey (hockey bling, blaow)", "Lil Uzi Vert"],
    ["Niggas think I'm weird and they don't really like me (like me)", "Lil Uzi Vert"],
    ["Ninety thousand, that's a light band, yeah (ninety thousand that's a light)", "Lil Uzi Vert"],
    ["I can tell you, it's the real spill (I can tell you, it's the real)", "Lil Uzi Vert"],
    ["Yeah, fucked your bitch just for a light bill (yeah)", "Lil Uzi Vert"],
    ["Yeah, banana clip, I won't slip on the peel (yeah)", "Lil Uzi Vert"],
    ["And I can't slip, slip, slip, no, no, I can't miss", "Lil Uzi Vert"],
    ["I got icebergs on my neck, I can sink a ship", "Lil Uzi Vert"],
    ["Outer space swag, not regular, Titanic my whip", "Lil Uzi Vert"],
    ["In the hood I'm not regular, I just brought my stick, baby", "Lil Uzi Vert"],
    ["Oh, you think I give a fuck because I'm rich, baby?", "Lil Uzi Vert"],
    ["Come on, baby, let's have sex and have a rich baby", "Lil Uzi Vert"],
    ["She said, \"I thought you ain't do that, \" well, you dismissed, baby (bye-bye)", "Lil Uzi Vert"],
    ["Uh, young nigga know I ain't changed, Lil Uzi from the 6', baby (yeah)", "Lil Uzi Vert"],
    ["Uh, I don't think they like me (nah)", "Lil Uzi Vert"],
    ["But when I drop this song I know they'll get excited (yeah)", "Lil Uzi Vert"],
    ["She was homie girl, but now that girl is my bitch (mine)", "Lil Uzi Vert"],
    ["I like them girls that do that scammin' and that swipin'", "Lil Uzi Vert"],
    ["I just ran up all my bands, I just ran up all my bands", "Lil Uzi Vert"],
    ["She give me head, that bitch migraine (migraine)", "Lil Uzi Vert"],
    ["She give me head, that bitch migraine (let's go)", "Lil Uzi Vert"],
    ["Got addicted to the road, got addicted to the stress", "Lil Uzi Vert"],
    ["Got addicted to the foreigns, got addicted to the racks (racks)", "Lil Uzi Vert"],
    ["Man, these boys be doin' the most", "Lil Uzi Vert"],
    ["And I swear that is a fact", "Lil Uzi Vert"],
    ["Man, this girl wanna give me brain", "Lil Uzi Vert"],
    ["Yeah, we call that bitch migraine", "Lil Uzi Vert"],
    ["Yeah, we call that bitch migraine (yeah, yeah)", "Lil Uzi Vert"],
    ["Yeah, we call that bitch migraine (ayy)", "Lil Uzi Vert"],
    ["Yeah, we call that bitch migraine", "Lil Uzi Vert"],
    ["Pack all my shit, then I might migrate", "Lil Uzi Vert"],
    ["Anywhere you goin', know some niggas gon' hate", "Lil Uzi Vert"],
    ["I don't run from shit but the damn police", "Lil Uzi Vert"],
    ["All blue hunnids to wash my face, yeah", "Lil Uzi Vert"],
    ["Stay so fresh, so clean, think they like me (like me)", "Lil Uzi Vert"],
    ["I wear more Supreme than a hypebeast (than a hypebeast)", "Lil Uzi Vert"],
    ["Only blue, no green don't excite me (excite me)", "Lil Uzi Vert"],
    ["I could make a ho out your wifey (out your wifey)", "Lil Uzi Vert"],
    ["Jeremy Scott up on my toes, act like Shockey (whoa)", "Lil Uzi Vert"],
    ["Made her get down on the bottom and she top me (let's go)", "Lil Uzi Vert"],
    ["Pull up extra icy, I'm not playin' hockey (bling, blaow)", "Lil Uzi Vert"],
    ["Niggas think I'm weird and they don't really like me (like me)", "Lil Uzi Vert"],
    ["Ice on, all my ice on (Skrr, skrr)", "Deko"],
    ["My dear, haver no fear", "Deko"],
    ["Made one thing clear", "Deko"],
    ["I'm not from here, I'm not from here, no", "Deko"],
    ["All my ice is on (Is on)", "Deko"],
    ["(Moonkid) Moonkid shine bright, so bright, all bright", "Deko"],
    ["Drop, drop with the top with a bop or some", "Deko"],
    ["Light up, with the opps, fuck the cops or some", "Deko"],
    ["Undefeated, man I cannot take a loss or some", "Deko"],
    ["(Hey) comi'n up again I'm couthing lotes of money, ayy", "Deko"],
    ["And I stand Alone", "Deko"],
    ["Rock so damn loud, fuck a microphone (Fuck it)", "Deko"],
    ["Bitch ride dick juts like a bicycle(Yah)", "Deko"],
    ["Tryna pull out but it seems Impossible (Okay)", "Deko"],
    ["I can pop on my babe with my fourteen chains", "Deko"],
    ["I make sure If you a lame, you ain't fucking hanging", "Deko"],
    ["If your the fuckin' same, then you cant not Bang with (Okay)", "Deko"],
    ["Young And independent bitch, you know that it's dangerous (Uh)", "Deko"],
    ["Ice on, all my ice on (Skrr, skrr)", "Deko"],
    ["My dear, haver no fear", "Deko"],
    ["Made one thing clear", "Deko"],
    ["I'm not from here, I'm not from here, no", "Deko"],
    ["All my ice is on (Is on)", "Deko"],
    ["(Moonkid) Moonkid shine bright, so bright, all night", "Deko"],
    ["Drop, drop with the top with a bop or some", "Deko"],
    ["Light up, with the opps, fuck the cops or some", "Deko"],
    ["Undefeated, man I cannot take a loss or some", "Deko"],
    ["(Hey) comi'n up again I'm couthing lotes of money, ayy", "Deko"],
    ["And the coupe Is stainless", "Deko"],
    ["Ride whith a bad bitch, give me neck on brainless, hey", "Deko"],
    ["Strainght upon the line, dat bih' don't need maintenance, hey (Uh)", "Deko"],
    ["Fucking It up when I switch my Cadence (Yuh, pew-pew-pew)", "Deko"],
    ["Oh, that's why my flow's contagious", "Deko"],
    ["Ball so hard need a fucking Sporting agent", "Deko"],
    ["Whithe weezy sound like I cam from New Orleans, ain't It?", "Deko"],
    ["But I'm strainght up out Atlanta", "Deko"],
    ["Bitch you Know I ain't changing (Yeah)", "Deko"],
    ["I love my city", "Deko"],
    ["I know no one no better", "Deko"],
    ["I never change me", "Deko"],
    ["No, that's the recipe", "Deko"],
    ["Neve get the best of me", "Deko"],
    ["Ice on, all my ice on (Skrr, skrr)", "Deko"],
    ["My dear, haver no fear", "Deko"],
    ["Made one thing clear", "Deko"],
    ["I'm not from here, I'm not from here, no", "Deko"],
    ["All my ice is on (Is on)", "Deko"],
    ["(Moonkid) Moonkid shine bright, so bright, all bright", "Deko"],
    ["Drop Drop with the top with a bop or some", "Deko"],
    ["Light up, with the opps, fuck the cops or some", "Deko"],
    ["Undefeated, man I cannot take a loss or some", "Deko"],
    ["(Hey) comi'n up again I'm couthing lotes of money, ayy", "Deko"],
    ["Smokin on the fronto", "Max Gertler (of Delivery Boys)"],
    ["You blow with no job", "Max Gertler (of Delivery Boys)"],
    ["I just wrote a new verse this ones for floam God", "Max Gertler (of Delivery Boys)"],
    ["She just took her clothes off", "Max Gertler (of Delivery Boys)"],
    ["She be my princess", "Max Gertler (of Delivery Boys)"],
    ["Now I'm off the ganzo", "Max Gertler (of Delivery Boys)"],
    ["I gotta think less", "Max Gertler (of Delivery Boys)"],
    ["Pull off in a range rove", "Goldwood"],
    ["Rock a fur kangol", "Goldwood"],
    ["Call me cinematographer I shoot at every angle", "Goldwood"],
    ["On the monitor iconic like an angel", "Goldwood"],
    ["Poised so fresh Man my crib is so palatial", "Goldwood"],
    ["Iced out wrist piss bitch it's feelin glacial", "Goldwood"],
    ["Cops Tryna claim that their bias not racial", "Goldwood"],
    ["Pull up on a pig opp fist to his nasal", "Goldwood"],
    ["Put em in the oven on da pizza like a basil", "Goldwood"],
    ["Cover her in butter poppy seed bagel", "Goldwood"],
    ["* nut abundant all my facials end up fatal", "Goldwood"],
    ["I'm stunting world wide just cuz I'm able", "Goldwood"],
    ["Tokyo to 6 like a Japanese maple", "Goldwood"],
    ["Man I'm rockin dicks out for harambe", "Goldwood"],
    ["I ain't gon dick u on a Sunday that gods day", "Goldwood"],
    ["Catching plays come catch me on Broadway", "Goldwood"],
    ["Gettin sippy off the liquor lickin Bombay", "Goldwood"],
    ["Gold tucked in chickens Tryna fuck him", "Goldwood"],
    ["Man delivery severely corrupted", "Goldwood"],
    ["It's an oligarchy", "Goldwood"],
    ["So we all gon party", "Goldwood"],
    ["Mother fuck space ghost shout out little sharky", "Goldwood"],
    ["Mother fucker Gimmie greenest of the crop", "Goldwood"],
    ["Smokin out the ounce bitch smokin fuckin pot", "Goldwood"],
    ["We never gon stop", "Goldwood"],
    ["We don't sleep", "Goldwood"],
    ["Workin hard til everybody be knowin me", "Goldwood"],
    ["Ay bitch, Gravy off probation", "Yung Gravy"],
    ["Fuck a PO, fuck a piss test, you feel me", "Yung Gravy"],
    ["Gravy on probation, now I'm off probation", "Yung Gravy"],
    ["Ayyyy, and I'm fucking with some Asians, ay", "Yung Gravy"],
    ["I said 1 thot, 2 thot, red thot, blue thot", "Yung Gravy"],
    ["Gravy so cold, bitch I think I need a flu shot", "Yung Gravy"],
    ["1 thot, 2 thot, 3 thot, 4 thot", "Yung Gravy"],
    ["Got yo bitch in the kitchen cooking up the pork chops", "Yung Gravy"],
    ["1 thot, 2 thot, red thot, blue thot", "Yung Gravy"],
    ["Gravy so cold bitch I think I need a flu shot", "Yung Gravy"],
    ["1 thot, 2 thot, 3 thot, 4 thot", "Yung Gravy"],
    ["Got your bitch in the kitchen cooking up the pork chops", "Yung Gravy"],
    ["I can tell your girl want it but I ain't tryna tempt her", "Yung Gravy"],
    ["Need my money now like I'm JG Wentworth", "Yung Gravy"],
    ["Bitch I does it, yeah I fuckin' does it", "Yung Gravy"],
    ["Posted with your auntie and your sister and your cousin", "Yung Gravy"],
    ["12 thotties cooking for me thats a bakers dozen", "Yung Gravy"],
    ["And they tryna show me ass putting cookies in the oven", "Yung Gravy"],
    ["They give me loving, they give me fuckin' loving", "Yung Gravy"],
    ["Team up on the cookies so they start to make the muffins", "Yung Gravy"],
    ["On that mountain top getting mountain top", "Yung Gravy"],
    ["Gravy might splash like a fountain on your thot", "Yung Gravy"],
    ["On that mountain top getting mountain top", "Yung Gravy"],
    ["Gravy might splash like a fountain on yur thot", "Yung Gravy"],
    ["I said 1 thot, 2 thot, red thot, blue thot", "Yung Gravy"],
    ["Gravy so cold, bitch I think I need a flu shot", "Yung Gravy"],
    ["1 thot, 2 thot, 3 thot, 4 thot", "Yung Gravy"],
    ["Got your bitch in the kitchen cooking up the pork chops", "Yung Gravy"],
    ["1 thot, 2 thot, red thot, blue thot", "Yung Gravy"],
    ["Gravy so cold bitch I think I need a flu shot", "Yung Gravy"],
    ["1 thot, 2 thot, 3 thot, 4 thot", "Yung Gravy"],
    ["Got your bitch in the kitchen cooking up the pork chops", "Yung Gravy"],
    ["Gravy make it splash like Pippen", "Yung Gravy"],
    ["Shit that’s nothin' (Splash)", "Yung Gravy"],
    ["Everybody call me Big Pimpin'", "Yung Gravy"],
    ["No, I ain't bluffin'", "Yung Gravy"],
    ["I'm with your mom in the kitchen", "Yung Gravy"],
    ["Makin' blueberry muffins (Mm)", "Yung Gravy"],
    ["Must be Thanksgiving", "Yung Gravy"],
    ["'Cause your bitch want the stuffing", "Yung Gravy"],
    ["Mr. Clean", "Yung Gravy"],
    ["Gravy why your flow so mean?", "Yung Gravy"],
    ["Pull up with my whole damn team", "Yung Gravy"],
    ["Gravy, he be clean like Windex (Woo)", "Yung Gravy"],
    ["Just hit your mom with my index (Woo)", "Yung Gravy"],
    ["And yo bitch look like a pinhead", "Yung Gravy"],
    ["All my haters, they be skinheads", "Yung Gravy"],
    ["Pissed off 'cause they wife is they sister", "Yung Gravy"],
    ["And Yung Gravy just kissed her (Hot damn)", "Yung Gravy"],
    ["Pull up on the scene", "Yung Gravy"],
    ["Cause a wet dream I might need a submarine", "Yung Gravy"],
    ["If you got the beef I turn yo ass to smitherines (Uh)", "Yung Gravy"],
    ["Yo bitch looking scary I thought it was Halloween", "Yung Gravy"],
    ["Gravy, he be clean like some fucking Listerine (Uh)", "Yung Gravy"],
    ["But I smooth it out like a jar of Vaseline, shit", "Yung Gravy"],
    ["Posted with a MILF and her name is Charlene", "Yung Gravy"],
    ["Errybody wonder how she got the hygiene", "Yung Gravy"],
    ["It's all thanks to Mr. Clean", "Yung Gravy"],
    ["Gravy why your flow so mean?", "Yung Gravy"],
    ["Pull up with my whole damn team", "Yung Gravy"],
    ["Gravy, he be clean like Colgate (Ayy)", "Yung Gravy"],
    ["White MILF Charlene that's my soulmate (Ayy)", "Yung Gravy"],
    ["You ain't got a bitch I might donate (Ayy)", "Yung Gravy"],
    ["Slide in the DMs with the snowflake (Ayy)", "Yung Gravy"],
    ["Talkin 'bout your girl my favorite topic", "Yung Gravy"],
    ["You can't even see me, you would think I'm microscopic", "Yung Gravy"],
    ["Gravy ballin' out like the fuckin' Flint Tropics", "Yung Gravy"],
    ["Turn these bitches on 'cause I'm really good at Bop-It", "Yung Gravy"],
    ["Clean in, clean out", "Yung Gravy"],
    ["Pullin' up drop top Viper (Ayy)", "Yung Gravy"],
    ["Had to steal yo bitch (Uh)", "Yung Gravy"],
    ["Finessed it like I'm Swiper (Ayy)", "Yung Gravy"],
    ["So much bread gotta get my fiber", "Yung Gravy"],
    ["Gravy, he be cleaner than your windshield wipers (Uh)", "Yung Gravy"],
    ["Your step-mom made me a pie", "Yung Gravy"],
    ["You can call me the Pied-Piper (Sheesh)", "Yung Gravy"],
    ["I don't eat the booty, I ain't even gotta say it", "Yung Gravy"],
    ["But I'll eat my girl's ass if she had a bad day (Ayy)", "Yung Gravy"],
    ["Gravy don't play", "Yung Gravy"],
    ["Bitch I'm at the bakery, them donuts gettin' glazed", "Yung Gravy"],
    ["Stay with three hoes like it's the holidays", "Yung Gravy"],
    ["Stuck to the bread, you would think I’m mayonnaise (Goddamn)", "Yung Gravy"],
    ["Shit I'm so God damn clean, got me feelin' like I'm Billy Mays", "Yung Gravy"],
    ["Gravy why your flow so mean?", "Yung Gravy"],
    ["Pull up with my whole damn team", "Yung Gravy"],
    ["It's getting serious", "Yung Gravy"],
    ["Make a bitch delirious", "Yung Gravy"],
    ["Bitches on my dick cause a boy so mysterious (woah)", "Yung Gravy"],
    ["That's a mystery", "Yung Gravy"],
    ["Thots makin' history", "Yung Gravy"],
    ["Wrist keep spinnin' like a fuckin' rotisserie (skrr)", "Yung Gravy"],
    ["Got my wrist whippin' (whippin')", "Yung Gravy"],
    ["Lookin' like a chef (chef)", "Yung Gravy"],
    ["Oregano in my right, 30 on my left (yeah)", "Yung Gravy"],
    ["Pull up with the set, got the kitchen all wet", "Yung Gravy"],
    ["And the cream team comin' for your neck (lil' bitch, ooh)", "Yung Gravy"],
    ["I don't do shit, but my bitch got tits (tits)", "Yung Gravy"],
    ["Gravy walk around lookin' like a fucking lick (lick)", "Yung Gravy"],
    ["Side bitch thick and my main bitch thick", "Yung Gravy"],
    ["And my oatmeal thick, bitch, I can't even pick (whoo)", "Yung Gravy"],
    ["Gravy be finnesin', it's a blessin' when I'm on the block", "Yung Gravy"],
    ["Teach your boy a lesson 'bout the flexin', bitches on a jock", "Yung Gravy"],
    ["Wrist so reflective, it's aggressive for a fuckin' clock", "Yung Gravy"],
    ["I been pourin' dressin' and caressin' on your fuckin' thot", "Yung Gravy"],
    ["Shit man, what I been up to?", "Yung Gravy"],
    ["A little bit of flexing", "Yung Gravy"],
    ["A little bit of good old fashion flexing (Whoa)", "Yung Gravy"],
    ["If you fucking with the team we gon' come and getcha (Gon' getcha)", "Yung Gravy"],
    ["Teach you something 'bout your girl, call that shit a lecture (A lecture)", "Yung Gravy"],
    ["Gravy so smooth you can check the fucking texture (Whoa)", "Yung Gravy"],
    ["You might see me pull up in my motherfuckin' sketchers (Ayy)", "Yung Gravy"],
    ["Got cheddar, you betcha", "Yung Gravy"],
    ["Gettin' to the cheese like Chester", "Yung Gravy"],
    ["Yung flexer, you betcha", "Yung Gravy"],
    ["Always in the clean striped sweater", "Yung Gravy"],
    ["Finesser, you betcha", "Yung Gravy"],
    ["Mighta' just piped your ancestor", "Yung Gravy"],
    ["I got Debra in the Tesla, too much sauce got extra", "Yung Gravy"],
    ["Yeah, I'm posted with your momma and your sister and your mofuckin granny, feelin' so dandy", "Yung Gravy"],
    ["Man, I'm sweet like candy", "Yung Gravy"],
    ["But I'm a savage like Randy, yo girl getting handsy", "Yung Gravy"],
    ["Tryna hit the beach get sandy, with the beach-side brandy", "Yung Gravy"],
    ["Boy you're a pansy, I hit your mom in the pantry", "Yung Gravy"],
    ["Gravy get it steamy like Stanley", "Yung Gravy"],
    ["I just fucked your bitch in some Louis V Crocs (Crocs?)", "Yung Gravy"],
    ["She couldn't resist cause I wore 'em with the socks (Socks?)", "Yung Gravy"],
    ["Now she won't get off my jock, had to finesse like I'm Brock", "Yung Gravy"],
    ["I get that drip from my Wok, I got your side bitch on lock", "Yung Gravy"],
    ["I always roll with a flock (Whoa)", "Yung Gravy"],
    ["Got the herbs with the spices, stole your girl that's a crisis", "Yung Gravy"],
    ["Had the pineapple slices, just got my finesse licence (Gravy Train)", "Yung Gravy"],
    ["Think I'm real cold like dicing, Gravy so enticing", "Yung Gravy"],
    ["I'll knock your ass out, Mike Tyson", "Yung Gravy"],
    ["I'm quick like lightning, bitch thicker than a fucking bison", "Yung Gravy"],
    ["I cover up the booty with Icing", "Yung Gravy"],
    ["If you fucking with the team we gon' come and getcha (Gon' getcha)", "Yung Gravy"],
    ["Teach you something 'bout your girl, call that shit a lecture (A lecture)", "Yung Gravy"],
    ["Gravy so smooth you can check the fucking texture (Whoa)", "Yung Gravy"],
    ["You might see me pull up in my motherfuckin' sketchers (Gravy Train)", "Yung Gravy"],
    ["Got cheddar, you betcha", "Yung Gravy"],
    ["Gettin' to the cheese like Chester", "Yung Gravy"],
    ["Yung flexer, you betcha", "Yung Gravy"],
    ["Always in the clean striped sweater", "Yung Gravy"],
    ["Finesser, you betcha", "Yung Gravy"],
    ["Mighta' just piped your ancestor", "Yung Gravy"],
    ["I got Debra in the Tesla, too much sauce got extra", "Yung Gravy"],
    ["Too much sauce got extra", "ihatesunday"],
    ["You can catch me in the lab like Dexter", "ihatesunday"],
    ["Your main bitch, yeah I sexed her only did it 'cause she look like Carmen Electra (Ayy)", "ihatesunday"],
    ["Tell her her friends all invited (Yuh)", "ihatesunday"],
    ["I got these white hoes excited (Ayy)", "ihatesunday"],
    ["Winona the way that I'm ridin', I'm vibin'", "ihatesunday"],
    ["I pop pills like I'm suicidal, I might be", "ihatesunday"],
    ["I'll make your mother my wifey", "ihatesunday"],
    ["Don't try me, you fucking need to see your ID", "ihatesunday"],
    ["It's sunday, or you can call me yung church house (Yeah)", "ihatesunday"],
    ["I fucked your bitch from my workout and I'll make your sister my daughter (Yeah)", "ihatesunday"],
    ["I'm feeling like I'm Dwayne Carter (Yuh)", "ihatesunday"],
    ["I gave your bitch a Dwayne Johnson", "ihatesunday"],
    ["I'm in her throat like a tonsil (Yeah)", "ihatesunday"],
    ["Watch your mouth when you lettin' shit slide", "6LACK"],
    ["Don't you know I got way too much pride?", "6LACK"],
    ["Sneak dissin' way on the other side", "6LACK"],
    ["I turn your fucking wave to a tide", "6LACK"],
    ["I'm so fucking tired", "6LACK"],
    ["Somehow I still find the time", "6LACK"],
    ["To care a little more about my rhymes", "6LACK"],
    ["To care a little more about my peers", "6LACK"],
    ["To think a lil' less about my fears", "6LACK"],
    ["To care a lil' more about your ears", "6LACK"],
    ["I give a piece of me to everybody I meet", "6LACK"],
    ["Not because they want it, it's because it's prolly a need", "6LACK"],
    ["Claim they woke but they probably asleep, in a cage", "6LACK"],
    ["Thinking if they make a mil they be free like Meek, nah", "6LACK"],
    ["I turned a nightmare right into a dream, yeah", "6LACK"],
    ["I keep my sanity, 'cause I ain't on the scene, yeah", "6LACK"],
    ["I know I gotta be a rock like Dwayne", "6LACK"],
    ["So, I'm tryna be a rock like Dwayne Carter, Rebirth", "6LACK"],
    ["Put that line in reverse, add a little reverb, yeah", "6LACK"],
    ["We work, so my niggas ain't gotta be on T-shirts", "6LACK"],
    ["Watch me get my hands dirty with the rework", "6LACK"],
    ["Damn, do I even have the fans for this shit?", "6LACK"],
    ["To be rapping like these people understanding this shit", "6LACK"],
    ["It's demanding and shit, but I stand for these kids", "6LACK"],
    ["Like they Stan for the kid, understand, now we clear", "6LACK"],
    ["Crack a beer when I'm feelin' pissed, hmm, yeah", "6LACK"],
    ["But I ain't got nobody hand up my back, you ventriloquist", "6LACK"],
    ["Ever since my songs went platinum like Sisqó", "6LACK"],
    ["Life done found a filter like VSCO, ay", "6LACK"],
    ["But it's okay, 'cause", "6LACK"],
    ["If you down and you need a lil' help, it's a way", "6LACK"],
    ["If you hatin' and you feelin' insecure, Issa Rae", "6LACK"],
    ["I'm somewhere between humble and hell nah", "6LACK"],
    ["These niggas drop their second album then fell off", "6LACK"],
    ["My nonchalant flow will never end right", "6LACK"],
    ["It be at they necks if it's in sight", "6LACK"],
    ["Squeezin' until they crack a windpipe", "6LACK"],
    ["Loosen the grip, have a lil' remorse", "6LACK"],
    ["You dial 9-1-1, I pull up in a Porsche", "6LACK"],
    ["Word is I'm carrying the torch and I ain't wanna share", "6LACK"],
    ["So beware if you reach you get scorched", "6LACK"],
    ["Ever since I jumped off the porch", "6LACK"],
    ["I knew that I would grow to be the boy", "6LACK"],
    ["The boy then grew to be the man", "6LACK"],
    ["Learned how to kill a hook, Peter Pan", "6LACK"],
    ["I'm tryna make the end stand out", "6LACK"],
    ["But I'm so fucking outstanding", "6LACK"],
    ["I'm so fucking outlandish and a opp can't win", "6LACK"],
    ["Man's not hot", "6LACK"],
    ["I been on ten, landslide wins, yeah", "6LACK"]
]