module.exports.chars = [
    ["https://oyster.ignimgs.com/mediawiki/apis.ign.com/deltarune/b/b4/Kris.jpg", "Kris"],
    ["https://oyster.ignimgs.com/mediawiki/apis.ign.com/deltarune/9/96/Susie.jpg?width=640", "Susie"],
    ["https://i.pinimg.com/originals/c7/b9/88/c7b98896072e7f3bcfaed682f48adaa3.jpg", "Ralsei"],
    ["https://vignette.wikia.nocookie.net/undertale/images/4/44/Sansanimated.gif/revision/latest/scale-to-width-down/118?cb=20181110100334","Sans"],
    ["https://vignette.wikia.nocookie.net/undertale/images/0/05/Flowey_battle_talk.gif/revision/latest/scale-to-width-down/90?cb=20151202211125","Flowey"],
    ["https://vignette.wikia.nocookie.net/mario/images/d/d2/781px-Mario_New_Super_Mario_Bros_U_Deluxe.png", "Mario"],
    ["https://vignette.wikia.nocookie.net/mario/images/a/a6/Princess_Peach_SMP.png/", "Peach"],
    ["https://vignette.wikia.nocookie.net/mario/images/d/d8/Shy_Guy_TT.png/", "ShyGuy"],
    ["https://vignette.wikia.nocookie.net/mario/images/8/8f/1200px-BowserNSMBUDX.png/revision/latest/top-crop/width/200/height/150?cb=20190620160446", "Bowser"],
    ["https://vignette.wikia.nocookie.net/mario/images/4/46/Princess_daisy_MKT.png/revision/latest/top-crop/width/200/height/150?cb=20200101144759", "Daisy"],
    ["https://vignette.wikia.nocookie.net/mario/images/9/9d/Luigi_%28Mario_Golf_World_Tour%29.png/revision/latest/scale-to-width-down/100?cb=20140504205407", "Luigi"],
    ["https://vignette.wikia.nocookie.net/half-life/images/4/41/G-Man_Alyx_Trailer.jpg/revision/latest/top-crop/width/200/height/150?cb=20191122020607&path-prefix=en", "G-Man"],
    ["https://vignette.wikia.nocookie.net/half-life/images/f/f3/Gordon_Freeman_%28Template%29.jpg/revision/latest/top-crop/width/200/height/150?cb=20191221105246&path-prefix=en", "Gordon"],
    ["https://vignette.wikia.nocookie.net/half-life/images/a/a4/Chell_Portal.png/revision/latest/top-crop/width/200/height/150?cb=20120621160758&path-prefix=en", "Chell"],
    ["https://vignette.wikia.nocookie.net/half-life/images/2/2e/Breen_upset.jpg/revision/latest/top-crop/width/200/height/150?cb=20200304071058&path-prefix=en", "WallanceBreen"],
    ["https://vignette.wikia.nocookie.net/half-life/images/7/77/YoungAlyxVance.jpg/revision/latest/top-crop/width/200/height/150?cb=20200323221922&path-prefix=en", "Alyx"],
    ["https://vignette.wikia.nocookie.net/half-life/images/6/6c/Barney_Calhoun_%28Template%29.jpg/revision/latest/top-crop/width/200/height/150?cb=20191221113101&path-prefix=en", "Barney"],
    ["https://vignette.wikia.nocookie.net/characters/images/b/b3/SteveMinecraft.png/revision/latest/top-crop/width/200/height/150?cb=20160127082617", "Steve"],
    ["https://vignette.wikia.nocookie.net/characters/images/b/b4/Herobrine.png/revision/latest/top-crop/width/200/height/150?cb=20180205181827", "Herobrine"],
    ["https://www.pngitem.com/pimgs/m/70-707291_anime-character-png-sao-yuuki-transparent-png-download.png", "Yuuki"],
    ["https://vignette.wikia.nocookie.net/darling-in-the-franxx/images/b/b3/Zero_Two_appearance.jpg/", "ZeroTwo"],
    ["https://vignette.wikia.nocookie.net/mudae/images/3/3d/Rem%241.png", "Rem"],
    ["https://vignette.wikia.nocookie.net/mudae/images/0/07/Chaser1.png", "Chaser"],
    ["https://vignette.wikia.nocookie.net/darling-in-the-franxx/images/6/6c/Ichigo_receives_her_name.png", "Ichigo"],
    ["https://vignette.wikia.nocookie.net/mudae/images/8/86/Akame%241.png", "Akame"],
    ["https://vignette.wikia.nocookie.net/mudae/images/8/81/Craven1.png", "Craven"],
    ["https://vignette.wikia.nocookie.net/mudae/images/2/27/Edinburgh1.png", "Edinburgh"],
    ["https://vignette.wikia.nocookie.net/mudae/images/3/3b/Fiji1.png", "Fiji"],
    ["https://vignette.wikia.nocookie.net/mudae/images/4/43/Kazuki_Kazami1.png", "Kazuki"],
    ["https://vignette.wikia.nocookie.net/mudae/images/5/5f/MomoBeliaDeviluke_1.png", "Momo"],
    ["https://vignette.wikia.nocookie.net/mudae/images/0/0f/Rias_Gremory%241.png", "Rias"],
    ["https://vignette.wikia.nocookie.net/mudae/images/f/f3/Neptune1.png", "Neptune"],
    ["https://vignette.wikia.nocookie.net/mudae/images/6/6b/Saber%241.png", "Saber"],
    ["https://vignette.wikia.nocookie.net/darling-in-the-franxx/images/9/9b/KokoroShuffle.png", "Kokoro"],
    ["https://vignette.wikia.nocookie.net/akamegakill/images/0/0d/Mine_main.png", "Mine"],
    ["https://vignette.wikia.nocookie.net/mudae/images/1/14/Fusou_%28AL%291.png", "Fusou"],
    ["https://vignette.wikia.nocookie.net/mudae/images/3/31/Joon1.png", "Joon"],
    ["https://vignette.wikia.nocookie.net/mudae/images/a/a2/Kagari1.png/", "Kagari"],
    ["https://vignette.wikia.nocookie.net/mudae/images/b/be/TomokoKuroki_1.png/", "Tomoko"],
    ["https://vignette.wikia.nocookie.net/mudae/images/4/4a/Swiftsure1.png/", "Swiftsure"],
    ["https://vignette.wikia.nocookie.net/mudae/images/4/49/Mikuma1.png/", "Mikuma"],
    ["https://vignette.wikia.nocookie.net/mudae/images/1/1e/Portland1.png/", "Portland"],
    ["https://vignette.wikia.nocookie.net/mudae/images/f/ff/Phoenix1.png/", "Phoenix"],
    ["https://vignette.wikia.nocookie.net/mudae/images/1/16/Olive1.png/", "Olive"],
    ["https://vignette.wikia.nocookie.net/mudae/images/1/1a/Ibuki_Mioda%241.png/", "Ibuki"],
    ["https://cdn.discordapp.com/attachments/598891058298093600/701421570169503754/Emilia.png", "Emilia"]
];